apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-hello-app
  labels:
    app: hello-app
    tier: front-end

spec:
  template:
    metadata:
      name: hello-app
      labels:
        app: myapp
        tier: front-end

    spec:
      containers:
       - name: hello-app
         image: nmncube/hello-app
  
  replicas: 3
  selector:
    matchLabels:
       tier: front-end 